### ISSUE TITLE
C# wrapper - getList 

### ISSUE THREAD

**Issue by Bladixx** [E-goi/e-goi-wrappers#21]
Hi

When i use Protocol.Rest and call the method getList() with the correct arguments, it thows an 'System.NullReferenceException'

The stack trace  is:

   ```
at Egoi.EgoiMap..ctor(Dictionary`2 other)
   at Egoi.EgoiApiRestImpl.walkMap(Dictionary`2 map)
   at Egoi.EgoiApiRestImpl.walkValues(EgoiMap map)
   at Egoi.EgoiApiRestImpl.walkMap(Dictionary`2 map)
   at Egoi.EgoiApiRestImpl.decodeMapListResult(String method, EgoiMap arguments)
   at Egoi.EgoiApiRestImpl.getLists(EgoiMap arguments)
 
```

Thanks
Ricardo

**Comment by renato-gomes** [comment]
Hello, sorry for the late reply.
We will be releasing the new C# SDK for our API V3 this quarter.
